# Generated by Django 2.1.4 on 2019-01-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190103_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
