# Generated by Django 2.1.4 on 2019-01-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='Test', max_length=200),
        ),
    ]
