# Generated by Django 2.1.4 on 2019-01-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
