# Generated by Django 2.1.4 on 2018-12-30 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnswerWords', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyapp.Question')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserFocusQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyapp.Question')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyapp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='questiontouser',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyapp.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='AnswerOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyapp.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='AnswerToQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyapp.Question'),
        ),
    ]
