# Generated by Django 2.1.4 on 2018-12-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0003_answer_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=200),
        ),
    ]
